src/Teams/Stubs/routes/web.php
// Team routes
Route::group([ 'namespace' => 'Teams' ], function() {
    Route::resource('team', 'TeamController');
    Route::name('team.switch')->get('team/switch/{team}', 'TeamController@switch');

    Route::name('team.invite')->post('team/{team}/invite', 'InviteController@store');
    Route::name('team.invite.resend')->get('team/invite/resend/{invite}', 'InviteController@resend');
    Route::name('team.invite.accept')->get('team/invite/accept/{token}', 'InviteController@accept');
    Route::name('team.invite.ignore')->get('team/invite/ignore', 'InviteController@ignore');
    Route::name('team.invite.cancel')->delete('team/invite/cancel/{invite}', 'InviteController@destroy');

    Route::name('team.members.destroy')->delete('team/{team}/members/{user}', 'TeamMemberController@destroy');
});

src/Teams/Stubs/app/Team.php
<?php

namespace App;

use Elegon\Teams\Team as ElegonTeam;

class Team extends ElegonTeam
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [ 'name', 'owner_id' ];

    /**
     * Get the URL of the team's picture.
     *
     * @param  string|null  $value
     * @return string
     */
    public function getPhotoUrlAttribute($value)
    {
        return empty($value) ? url('images/default/team.svg') : url($value);
    }
}

src/Teams/Stubs/app/Http/Controllers/Teams/InviteController.php
<?php

namespace App\Http\Controllers\Teams;

use Auth;
use Mail;
use Elegon;
use App\Team;
use App\Mail\TeamInvite;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Elegon\Teams\Events\UserInvitedToTeam;

class InviteController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth')->except('accept', 'ignore');
        $this->middleware('can:sendInvite,team')->only('store');
        $this->authorizePolicy(Elegon::inviteModel());
    }

    /**
     * Invite a given user to join the team by email.
     */
    public function store(Request $request, Team $team)
    {
        $this->validate($request, [ 'email' => 'required|email' ]);

        if ($team->hasPendingInvite($request->email)) {
            return redirect()->back()->withErrors([
                'email' => 'The email address is already invited to the team.'
            ]);
        }

        $invite = $team->invite($request->email);

        if (! $invite) {
            return redirect()->back()->withErrors([
                'email' => 'The invite could not be created. Please try again later.'
            ]);
        }

        Mail::send(new TeamInvite($invite));
        event(new UserInvitedToTeam($invite));
        
        return redirect()->back();
    }

    /**
     * Resend an invitation mail.
     */
    public function resend($invite)
    {
        Mail::send(new TeamInvite($invite));

        flash()->success('Invitation has been resent.');

        return redirect()->route('team.show', $invite->team);
    }

    /**
     * Accept the given invite.
     */
    public function accept($token)
    {
        if (! ($invite = Elegon::invite()->findByToken($token))) {
            abort(404);
        }

        if (Auth::guest() || ! $invite->isFor(Auth::user())) {
            Auth::logout();
            session([ 'invite_token' => $token ]);
            return redirect()->route('register');
        }

        $invite->accept();
        flash()->success("You have joined {$invite->team->name}.");
        return redirect()->route('team.show', $invite->team);
    }

    /**
     * Ignore the invite token session variable given via email.
     */
    public function ignore()
    {
        session()->forget('invite_token');

        return redirect()->back();
    }

    /**
     * Cancel an invite that has not yet been accepted.
     */
    public function destroy($invite)
    {
        $invite->cancel();

        return redirect()->back();
    }
}

src/Teams/Stubs/app/Http/Controllers/Teams/TeamController.php
<?php

namespace App\Http\Controllers\Teams;

use Auth;
use App\Team;
use App\User;
use App\Jobs\StoreAvatar;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TeamController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->authorizePolicy(Team::class, [ 'switch' ]);
    }

    /**
     * Display a listing of the user's teams.
     */
    public function index()
    {
        return view('pages.team.index')->withTeams(Auth::user()->teams);
    }

    /**
     * Show the details and members of the given team.
     */
    public function show(Team $team)
    {
        return view('pages.team.show')->withTeam($team);
    }

    /**
     * Show the form for creating a new team.
     */
    public function create()
    {
        return view('pages.team.create');
    }

    /**
     * Store a newly created team in storage.
     */
    public function store(Request $request)
    {
        $team = Team::create([
            'name' => $request->name,
            'owner_id' => $request->user()->getKey()
        ]);

        $request->user()->attachTeam($team);

        return redirect()->route('team.show', $team);
    }

    /**
     * Show the form for editing the specified team.
     */
    public function edit(Team $team)
    {
        return view('pages.team.edit')->withTeam($team);
    }

    /**
     * Update the specified team in storage.
     */
    public function update(Request $request, Team $team)
    {
        $this->validate($request, [
            'name' => 'filled|max:191',
            'avatar' => 'filled|image|max:4000',
        ]);

        if ($request->hasFile('avatar')) {
            dispatch(new StoreAvatar($team, 'team_avatars', $request->file('avatar')));
        }

        $team->update($request->all());

        flash()->success("$team->name has been updated.");

        return redirect()->route('team.show', $team);
    }

    /**
     * Remove the specified team from storage.
     */
    public function destroy(Team $team)
    {
        $teamId = $team->id;
        $team->delete();

        User::where('current_team_id', $teamId)
            ->update([ 'current_team_id' => null ]);

        flash()->success("{$team->name} has been deleted.");

        return redirect()->route('team.index');
    }

    /**
     * Switch to the given team.
     */
    public function switch(Team $team)
    {
        Auth::user()->switchTeam($team);

        return redirect()->back();
    }
}

src/Teams/Stubs/app/Http/Controllers/Teams/TeamMemberController.php
<?php

namespace App\Http\Controllers\Teams;

use Auth;
use App\Team;
use App\User;
use App\Http\Controllers\Controller;
use Elegon\Teams\Events\UserLeftTeam;

class TeamMemberController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('can:deleteMember,team,user')->only('destroy');
    }

    /**
     * Remove the specified user from the given team.
     */
    public function destroy(Team $team, User $user)
    {
        $user->detachTeam($team);

        event(new UserLeftTeam($user, $team));

        if (Auth::user()->is($user)) {
            flash()->success("You have left {$team->name}.");
            return redirect()->route('team.index');
        }

        return redirect()->back();
    }
}

src/Teams/Stubs/resources/views/layouts/app/header/team.blade.php
@if (Auth::user()->teams()->exists())
    
    @if (Auth::user()->currentTeam)
        <div 
            class="ui simple dropdown item" 
            @click="window.location = '{{ route('team.show', Auth::user()->currentTeam) }}'"
        >
    @else
        <div class="ui simple dropdown item">
    @endif

        {{-- Current team button --}}
        @if (Auth::user()->currentTeam)
            {{ Auth::user()->currentTeam->name }}
        @else
            No current team
        @endif

        <i class="dropdown icon"></i>

        {{-- Dropdown menu --}}
        <div class="menu">

            {{-- Suggestions for switching team --}}
            @forelse (Auth::user()->teamSuggestions() as $team)
                <a class="item" href="{{ route('team.switch', $team) }}">
                    {{ $team->name }}
                </a>

            {{-- No other teams to suggest --}}
            @empty
                <a class="item" style="text-align: center;" href="{{ route('team.create') }}">
                    Create
                </a>
            @endforelse
            
            <div class="divider"></div>

            <a class="item" style="text-align: center;" href="{{ route('team.index') }}">
                See all
            </a>

        </div>
    </div>

@else

    {{-- User has no team --}}
    <a class="item" href="{{ route('team.create') }}">
        <i class="plus icon"></i> Create a team
    </a>

@endif

src/Teams/Stubs/resources/views/pages/team/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="ui container centered stackable grid">
        <div class="ten wide column">
            @component('components.shared.panel')
                @slot('header', 'Create a new team')

                <form class="ui form" method="POST" action="{{ route('team.store') }}">
                    {!! csrf_field() !!}

                    @component('components.shared.form.field', [ 'name' => 'name' ])
                        <input type="text" name="name" placeholder="Team Name" value="{{ old('name') }}">
                    @endcomponent

                    <input class="ui fluid button" type="submit" value="Create team">
                </form>
            @endcomponent
        </div>
    </div>
@endsection

src/Teams/Stubs/resources/views/pages/team/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="ui container centered stackable grid">

        <div class="four wide column">
            @include('pages.team.edit.avatar')
        </div>

        <div class="twelve wide column">
            @include('pages.team.edit.information')

            @include('pages.team.edit.modal-delete')
            <button class="ui fluid negative button" data-toggle="modal" data-target="#deleteModal">
                Delete {{ $team->name }}
            </button>
        </div>

    </div>
@endsection

src/Teams/Stubs/resources/views/pages/team/edit/avatar.blade.php
<div class="ui card">
    <div class="image">
        <img src="{{ $team->photo_url }}">
    </div>
    <div class="content">
        <form class="ui form" method="POST" action="{{ route('team.update', $team) }}" enctype="multipart/form-data">
            {{ method_field('PATCH') }}
            {{ csrf_field() }}

            @component('components.shared.form.field', [ 'name' => 'avatar' ])
                <input-file name="avatar"></input-file>
            @endcomponent

            <input class="ui fluid button" type="submit" value="Update team photo">
        </form>
    </div>
</div>

src/Teams/Stubs/resources/views/pages/team/edit/information.blade.php
@component('components.shared.panel')
    @slot('header', 'Main information')
    @slot('actions')
        <a class="ui tiny compact basic button" href="{{ route('team.show', $team) }}">cancel</a>
    @endslot

    <form class="ui form" method="POST" action="{{ route('team.update', $team) }}">
        {{ csrf_field() }}
        {{ method_field('PUT') }}

        @component('components.shared.form.field', [ 'name' => 'name' ])
            <input type="text" name="name" placeholder="Team Name" value="{{ old('name', $team->name) }}">
        @endcomponent

        <input class="ui fluid button" type="submit" value="Update team">
    </form>
@endcomponent

src/Teams/Stubs/resources/views/pages/team/edit/modal-delete.blade.php
<div id="deleteModal" class="ui basic small modal" style="text-align: center;">
    <div class="content">
        <h1>Are you sure?</h1>
        <p>This action cannot be undone.</p>

        @component('components.shared.form.delete', [ 'action' => route('team.destroy', $team) ])
            <div class="ui cancel button">Cancel</div>
            <input class="ui negative button" type="submit" value="Yes, delete {{ $team->name }}">
        @endcomponent
    </div>
</div>

src/Teams/Stubs/resources/views/pages/team/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="ui container centered stackable grid">
        <div class="ten wide column">

            <h4 class="ui top attached block level header">
                <span class="expand">My teams</span>
                <a class="ui tiny compact basic button" href="{{ route('team.create') }}">create</a>
            </h4>
            
            @if ($teams->isEmpty())
                @include('pages.team.index.no-team')
            @else
                @include('pages.team.index.team-list')
            @endif
        </div>
    </div>
@endsection

src/Teams/Stubs/resources/views/pages/team/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="ui container centered stackable grid">

        <div class="four wide column">
            @include('components.team.card')
        </div>

        <div class="twelve wide column">
            @include('pages.team.show.members')
            @include('pages.team.show.pending-invites')
            @include('pages.team.show.new-invite')
        </div>

    </div>
@endsection